name: 'Open Component Model actions'
description: 'Execute Open Component Model operations on project'
inputs:
  action:
    description: 'action to execute'
    required: true
  component:
    description: 'component name'
    required: false
  version:
    description: 'component version'
    required: false
  version_cmd:
    description: 'command used to extract actual version'
    required: false
  version_file:
    description: 'file to lookup the actual version'
    required: false
  directory:
    description: 'directory to store component information'
    required: false
  provider:
    description: 'provider name'
    required: false
  ctf:
    description: 'ctf file path'
    required: false
    default: 'gen/ocm/ctf'
  settings:
    description: 'settings file for resource add commands'
    required: false
  var_values:
    description: 'variable values (in yaml syntax) passed to templater'
    required: false
  resources:
    description: 'resource specification'
    required: false
  templater:
    description: 'Templater used for processing input files'
    required: false
  comprepo_url:
    description: component repository base url
    required: false
  comprepo_user:
    description: component repository user
    required: false
  comprepo_password:
    description: component repository password
    required: false
outputs:
  component-name:
    description: 'component name'
  component-version:
    description: 'component version'
  component-path:
    description: 'component path'
  transport-archive:
    description: 'transport archive path'
branding:
  color: 'blue'
runs:
  using: composite
  steps:
  - shell: bash
    env:
      ocm_settings: ${{ inputs.settings }}
      ocm_var_values: ${{ inputs.var_values }}
      ocm_resources: ${{ inputs.resources }}
      ocm_ctf: ${{ inputs.ctf }}
      ocm_component: ${{ inputs.component }}
      ocm_versioncmd: ${{ inputs.version_cmd }}
      ocm_versionfile: ${{ inputs.version_file }}
      ocm_componentversion: ${{ inputs.version }}
      ocm_provider: ${{ inputs.provider }}
      ocm_componentdir: ${{ inputs.directory }}
      ocm_templater: ${{ inputs.templater }}
      ocm_comprepo: ${{ inputs.comprepo_url }}
      ocm_comprepouser: ${{ inputs.comprepo_user }}
      ocm_comprepopassword: ${{ inputs.comprepo_password }}
    run: |
      echo "path: ${{ github.action_path }}"
      "${{ github.action_path }}/action.sh" "${{ inputs.action }}"
